<a href="https://colab.research.google.com/github/odesay97/MachineLearing_Class/blob/main/4_2_%EC%8B%A4%EC%8A%B5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [22]:
# 1. 데이터 준비
# 2. 클래스 추출
# 3. 입력데이터와 정답데이터를 생성햊보자
# 4. 훈련세트와 테스트세트로 나누자
# 5. 데이터 표준화
# 6. k최근접 이웃 알고지즘을 이용하여 훈련하고 훈련세트와 테스트세트에 대해 평가
# 7. 테스트세트의 5개의 데이터에 대해서 예측과 확률을 알아보자
# 8. 최적화해보자

# k 최근접
import pandas as pd
import numpy as np

data = pd.read_csv("https://raw.githubusercontent.com/jmnote/zdata/master/R/iris.csv")
print(data)

iris_train = data[['Sepal.Length','Sepal.Width','Petal.Length','Petal.Width']].to_numpy()
print(iris_train[:5])

iris_target = data['Species'].to_numpy()
print(iris_target[:5])

# 클래스 추출
print(np.unique(iris_target))

# 훈련세트 테스트세트 나누기 -> stratify 필수 ! -> 클래스 데이터를 기준으로 편향을 없애므로 아래와 같이

from sklearn.model_selection import train_test_split

train_input, test_input, train_target,test_target = train_test_split(iris_train, iris_target, stratify=iris_target, random_state=42)

# 정규화
from sklearn.preprocessing import StandardScaler

ss = StandardScaler()
ss.fit(train_input)
train_scaled = ss.transform(train_input)
test_scaled = ss.transform(test_input)

# k 최근접으로 훈련

from sklearn.neighbors import KNeighborsClassifier

kn = KNeighborsClassifier(n_neighbors = 3)
kn.fit(train_scaled,train_target)

# 평가
print(kn.score(train_scaled, train_target))
print(kn.score(test_scaled, test_target))

#  앞에 5개 예측
print(kn.predict(test_scaled[:5]))

# 확률
proba = kn.predict_proba(test_scaled[:5])
print(proba)


#-------------------------------------------------------

# 확률적 경사하강법

# 데이터 가져오기, 훈련세트 테스트세트 나누기, 정규화까지는 동일

# 확률적 경사하강법 훈련 ( 규제 로그로스 사용 )

from sklearn.linear_model import SGDClassifier

sgd = SGDClassifier(loss= 'log_loss',max_iter=100,tol = None, random_state=42)
sgd.fit(train_scaled,train_target)

print(sgd.score(train_scaled,train_target))
print(sgd.score(test_scaled,test_target))

from sklearn.linear_model import SGDClassifier

sgd = SGDClassifier(loss= 'hinge',max_iter=100,tol = None, random_state=42)
sgd.fit(train_scaled,train_target)

print(sgd.score(train_scaled,train_target))
print(sgd.score(test_scaled,test_target))

     Sepal.Length  Sepal.Width  Petal.Length  Petal.Width    Species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]
['setosa' 'setosa' 'setosa' 'setosa' 'setosa']
['set